### ISSUE TITLE
Support for SDMX-JSON 2.0.0

### ISSUE THREAD

**Issue by thhomas** [jsonstat/suite#3]
It seems that the function `fromSDMX` does not support SDMX-JSON 2.0.0 (cf [spec repo](https://github.com/sdmx-twg/sdmx-json/tree/master/data-message/tools/schemas)).
The main change is that `structure` at data level is now an array (`structures`) and every dataset has now a `structure` index.
[Here](https://stats-nsi-stable.pacificdata.org/rest/data/SPC,DF_COVID,1.0/M..CASES+DEATHS?startPeriod=2019-12&endPeriod=2022-07&lastNObservations=13&dimensionAtObservation=AllDimensions) is an example of an implementation of SDMX-JSON 2.0.0 (from dotstatsuite)

**Comment by badosa** [comment]
Thanks for spotting this. I'll try to address this issue soon.

**Comment by badosa** [comment]
@thhomas Could you provide a real SDMX-JSON v2 end-point? I could not find one (not even using Accept header application/vnd.sdmx.data+json;version=2.0.0). Your pacificdata.org URL returns XML and replacing /rest/ with /SDMX-JSON/ returns 404.

**Comment by thhomas** [comment]
@badosa have you tried to use the header on the URL I gave you.
`curl -H 'Accept: application/vnd.sdmx.data+json;version=2.0.0' "https://stats-nsi-stable.pacificdata.org/rest/data/SPC,DF_COVID,1.0/M..CASES+DEATHS?startPeriod=2019-12&endPeriod=2022-07&lastNObservations=13&dimensionAtObservation=AllDimensions"`
is working OK.

**Comment by badosa** [comment]
Sorry @thhomas: I assumed that, if 2.0.0 was supported by dotstatsuite, it would be used by oecd.org.

As you can guess, the interest on SDMX-JSON in the JSON-stat (a competing standard) community is low and support for SDMX-JSON in jsonstat-suite is not a priority. Meaning: it was never a goal to fully support the different SDMX-JSON flavors. It is, though, to help moving from SDMX-JSON responses in some of the most common flavors used by the main data providers to JSON-stat.

Because I'm assuming that sooner or later the main SDMX-JSON data providers will be using version 2.0.0, I updated jsonstat-suite: [fromSDMX](https://github.com/jsonstat/suite/blob/master/docs/fromsdmx.md) in jsonstat-suite v.3.2.5 experimentally supports SDMX-JSON v.2.0.0. Or as it is written in the docs:

> Objects with more than one dataset are not supported. Only SDMX-JSON with a flat list of observations without any grouping (dimensionAtObservation=allDimensions) is fully supported. Support for intermediate grouping of observations (series) is experimental. Support for SDMX-JSON version 2 is also experimental.

Because I could only try the new release with your single example, any feedback is welcome.
